### ISSUE TITLE
UnicodeDecodeError in filter_gap_SVs.py

### ISSUE THREAD

**Issue by Ritu-Kundu** [malonge/RaGOO#18]
Thanks for this awesome tool. I have successfully used it to reorder the contigs in my draft assembly. Now, I am trying to correct the misassemblies and call SVs. This attempt gives the following runtime error:
    

    Traceback (most recent call last):
      File "/home/rkundu/miniconda3/bin/filter_gap_SVs.py", line 4, in <module>
       __import__('pkg_resources').run_script('RaGOO==1.1', 'filter_gap_SVs.py')
      File "/home/rkundu/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
         self.require(requires)[0].run_script(script_name, ns)
       File "/home/rkundu/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
          exec(script_code, namespace, namespace)
       File "/home/rkundu/miniconda3/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/EGG-INFO/scripts/filter_gap_SVs.py", line 125, in <module>
       File "/home/rkundu/miniconda3/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/EGG-INFO/scripts/filter_gap_SVs.py", line 120, in main
       File "/home/rkundu/miniconda3/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/EGG-INFO/scripts/filter_gap_SVs.py", line 27, in make_gaps_tree
       File "/home/rkundu/miniconda3/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/ragoo_utilities/SeqReader.py", line 20, in parse_fasta
       File "/home/rkundu/miniconda3/lib/python3.6/codecs.py", line 321, in decode
           (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
    /home/rkundu/miniconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
       out=out, **kwargs)
    /home/rkundu/miniconda3/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
       ret = ret.dtype.type(ret / rcount)
    Traceback (most recent call last):
       File "/home/rkundu/miniconda3/bin/ragoo.py", line 4, in <module>
         __import__('pkg_resources').run_script('RaGOO==1.1', 'ragoo.py')
       File "/home/rkundu/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
         self.require(requires)[0].run_script(script_name, ns)
       File "/home/rkundu/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
         exec(script_code, namespace, namespace)
       File "/home/rkundu/miniconda3/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/EGG-INFO/scripts/ragoo.py", line 749, in <module>
       File "/home/rkundu/miniconda3/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/EGG-INFO/scripts/ragoo.py", line 475, in get_SVs
        File "/home/rkundu/miniconda3/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/ragoo_utilities/utilities.py", line 25, in run
    RuntimeError: Failed : filter_gap_SVs.py ../../GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

**Comment by malonge** [comment]
Hi there,

Thanks for pointing this out. The problem is that the rest of the piplein works fine with gzip files, but `filter_gap_SVs.py` does not work with the reference file gzipped. I will update the functionality of that python file then let you know when it is ready.

If you need results now, just gunzip your reference.

Thanks,
Mike

**Comment by Ritu-Kundu** [comment]
Hi,

That worked. Thanks a lot.

**Comment by evanrrees** [comment]
I ran into the same `UnicodeDecodeError` while running the main pipeline. It was resolved by decompressing input files but it seems that everything ran correctly prior to pseudomolecule creation. @malonge: per your comment above, I take it gzipped input should be acceptable?

```
Fri Sep 13 14:47:20 2019 --- Assigning contigs
Fri Sep 13 14:47:24 2019 --- Ordering and orienting contigs
Fri Sep 13 14:47:55 2019 --- Creating pseudomolecules
Traceback (most recent call last):
  File "/home/err87/miniconda3/envs/minimap/bin/ragoo.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.1', 'ragoo.py')
  File "/home/err87/miniconda3/envs/minimap/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/err87/miniconda3/envs/minimap/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/home/err87/miniconda3/envs/minimap/lib/python3.7/site-packages/RaGOO-1.1-py3.7.egg/EGG-INFO/scripts/ragoo.py", line 742, in <module>
  File "/home/err87/miniconda3/envs/minimap/lib/python3.7/site-packages/RaGOO-1.1-py3.7.egg/EGG-INFO/scripts/ragoo.py", line 322, in create_pseudomolecules
  File "/home/err87/miniconda3/envs/minimap/lib/python3.7/site-packages/RaGOO-1.1-py3.7.egg/ragoo_utilities/SeqReader.py", line 20, in parse_fasta
  File "/home/err87/miniconda3/envs/minimap/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

[1]+  Exit 1                  ragoo.py -t 38 data/contigs.fa.gz data/reference.fa.gz
```

**Comment by malonge** [comment]
Hi there,

Yeah I should allow for gz input but I know exactly what is going wrong here. Sorry about that. Could I trouble you to open this up as a separate GitHub issue? Then I will put it on the TODO list to add that capability. This particular feature should be fairly easy to enable. 

Thanks

**Comment by malonge** [comment]
Ok nevermind - everything should be fixed now in the following commit

381375b454d064a568595856f026257726dac205

I hope that everything is now fully gzip compatible. Let me know if you see otherwise.

Thanks!

**Comment by evanrrees** [comment]
@malonge Thank you! I will test and open a separate issue if necessary.
