### ISSUE TITLE
ValueError: IntervalTree

### ISSUE THREAD

**Issue by mictadlo** [malonge/RaGOO#32]
Hi, 
I ran into the following error:

```
Thu Oct 17 16:25:47 2019 --- Misassembly correction has been turned on. This automatically inactivates chimeric contig correction.
Thu Oct 17 16:25:47 2019 --- Running : minimap2 -k19 -w19 -t8 ../NbV1ChF.fasta ../Contigs.txt > contigs_against_ref.paf 2> contigs_against_ref.paf.log
Thu Oct 17 16:29:25 2019 --- Reading alignments
Thu Oct 17 16:34:00 2019 --- Getting gff features
Thu Oct 17 16:34:17 2019 --- Aligning raw reads to contigs
Thu Oct 17 16:34:17 2019 --- Running : minimap2 -x sr -t8 ../../Contigs.txt ../../1740D-43-05_S0_L001_R1.fastq > reads_against_ctg.paf 2> reads_against_ctg.paf.log
Thu Oct 17 21:27:31 2019 --- Computing contig coverage
Traceback (most recent call last):
  File "/work/waterhouse_team/miniconda2/envs/ragoo/bin/ragoo.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.1', 'ragoo.py')
  File "/work/waterhouse_team/miniconda2/envs/ragoo/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/work/waterhouse_team/miniconda2/envs/ragoo/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/work/waterhouse_team/miniconda2/envs/ragoo/lib/python3.7/site-packages/RaGOO-1.1-py3.7.egg/EGG-INFO/scripts/ragoo.py", line 714, in <module>
  File "/work/waterhouse_team/miniconda2/envs/ragoo/lib/python3.7/site-packages/RaGOO-1.1-py3.7.egg/EGG-INFO/scripts/ragoo.py", line 36, in update_misasm_features
  File "/work/waterhouse_team/miniconda2/envs/ragoo/lib/python3.7/site-packages/intervaltree/intervaltree.py", line 1060, in __setitem__
    self.addi(index.start, index.stop, value)
  File "/work/waterhouse_team/miniconda2/envs/ragoo/lib/python3.7/site-packages/intervaltree/intervaltree.py", line 343, in addi
    return self.add(Interval(begin, end, data))
  File "/work/waterhouse_team/miniconda2/envs/ragoo/lib/python3.7/site-packages/intervaltree/intervaltree.py", line 326, in add
    " {0}".format(interval)
ValueError: IntervalTree: Null Interval objects not allowed in IntervalTree: Interval(0, 0, (0, 0))
```
What possible could have caused the error?

Thank you in advance,

Michal

**Comment by malonge** [comment]
I'll take a look and get back to you. Sorry about that!

**Comment by malonge** [comment]
Hi there,

The problem seems to be that the misassembly correction algorithm is recommended a break at position 0 of a contig. It should only be recomending breakpoints that are at least 25kbp away from the start of end of the contig. I am looking into why this may be happening.

By chance, would you be willing to share your data with me to help the debugging?

**Comment by malonge** [comment]
I am going to close this issue, though please feel free to reopen it if anything comes up.

I would also encourage you to use RagTag for any future analysis:

https://github.com/malonge/RagTag

RagTag is the successor of RaGOO and it is much improved.

Thanks,
Mike
