### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by zhuangfjnu** [malonge/RaGOO#46]
Hi,
I ran into the following error:

ragoo.py outpre.ctg.lay.fa merge.ccs.fasta
Mon Jan 27 17:33:56 2020 --- Reading alignments
Mon Jan 27 17:37:10 2020 --- Assigning contigs
Traceback (most recent call last):
  File "/home/nfhy_huangz/miniconda2/envs/ragoo/bin/ragoo.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.1', 'ragoo.py')
  File "/home/nfhy_huangz/miniconda2/envs/ragoo/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/nfhy_huangz/miniconda2/envs/ragoo/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/home/nfhy_huangz/miniconda2/envs/ragoo/lib/python3.8/site-packages/RaGOO-1.1-py3.8.egg/EGG-INFO/scripts/ragoo.py", line 744, in <module>
  File "/home/nfhy_huangz/miniconda2/envs/ragoo/lib/python3.8/site-packages/RaGOO-1.1-py3.8.egg/EGG-INFO/scripts/ragoo.py", line 123, in write_contig_clusters
FileNotFoundError: [Errno 2] No such file or directory: 'm64031_200102_132349/172032446/ccs_contigs.txt'

What possible could have caused the error?

Thanks,
Zhen

**Comment by malonge** [comment]
Hi there,

Could you show me what is in your 'groupings' directory?

Also, could you show me some example fasta headers from `merge.ccs.fasta`?

Thanks

**Comment by zhuangfjnu** [comment]
Hi MIchael,
There is no file in the groupings directory.
the headers of merge.ccs.fasta are 
>m64031_200102_132349/178718244/ccs
>m64031_200102_132349/178718248/ccs
>m64031_200102_132349/178718250/ccs

Thanks

**Comment by zhuangfjnu** [comment]
Hi MIchael,
I put the wrong files (merge.ccs.fasta )as the reference file. 
Sorry about this issue.

Zhen
