### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by francicco** [malonge/RaGOO#5]
Hi,

I'm trying to install RaGOO using virtualenv, but even if the installation ended without errors or warnings ragoo.py seems not to be working

```
(Ragoo_env) [fc464@login-e-12 RaGOO]$ python ragoo.py 
Traceback (most recent call last):
  File "ragoo.py", line 8, in <module>
    from ragoo_utilities.ContigAlignment import ContigAlignment
  File "/home/fc464/software/RaGOO/ragoo_utilities/ContigAlignment.py", line 4, in <module>
    from ragoo_utilities.utilities import summarize_planesweep, binary_search
  File "/home/fc464/software/RaGOO/ragoo_utilities/utilities.py", line 9, in <module>
    complements = str.maketrans("ACGTNURYSWKMBVDHacgtnuryswkmbvdh", "TGCANAYRSWMKVBHDtgcanayrswmkvbhd")
AttributeError: type object 'str' has no attribute 'maketrans'
``` 
Am I miss something?
Thanks
F

**Comment by malonge** [comment]
Hi,

Can you verify that you are trying to install with python 3?

Thanks

**Comment by francicco** [comment]
This is what I do:

```
[fc464@login-e-10 RaGOO]$ virtualenv RaGOO_env
New python executable in /home/fc464/software/RaGOO/RaGOO_env/bin/python
Installing setuptools, pip, wheel...done.
[fc464@login-e-10 RaGOO]$ source RaGOO_env/bin/activate
(RaGOO_env) [fc464@login-e-10 RaGOO]$ pip install -e .
Obtaining file:///home/fc464/software/RaGOO
Collecting intervaltree (from RaGOO==1.2)
Collecting numpy (from RaGOO==1.2)
  Using cached https://files.pythonhosted.org/packages/c4/33/8ec8dcdb4ede5d453047bbdbd01916dbaccdb63e98bba60989718f5f0876/numpy-1.16.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting sortedcontainers<3.0,>=2.0 (from intervaltree->RaGOO==1.2)
  Using cached https://files.pythonhosted.org/packages/13/f3/cf85f7c3a2dbd1a515d51e1f1676d971abe41bba6f4ab5443240d9a78e5b/sortedcontainers-2.1.0-py2.py3-none-any.whl
Installing collected packages: sortedcontainers, intervaltree, numpy, RaGOO
  Running setup.py develop for RaGOO
Successfully installed RaGOO intervaltree-3.0.2 numpy-1.16.2 sortedcontainers-2.1.0
You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(RaGOO_env) [fc464@login-e-10 RaGOO]$ python setup.py install
/home/fc464/software/RaGOO/RaGOO_env/lib/python2.7/site-packages/setuptools/dist.py:331: UserWarning: Normalizing 'v1.02' to '1.2'
  normalized_version,
running install
running bdist_egg
running egg_info
writing requirements to RaGOO.egg-info/requires.txt
writing RaGOO.egg-info/PKG-INFO
writing top-level names to RaGOO.egg-info/top_level.txt
writing dependency_links to RaGOO.egg-info/dependency_links.txt
reading manifest file 'RaGOO.egg-info/SOURCES.txt'
writing manifest file 'RaGOO.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/ragoo_utilities
copying ragoo_utilities/SeqReader.py -> build/lib/ragoo_utilities
copying ragoo_utilities/GFFReader.py -> build/lib/ragoo_utilities
copying ragoo_utilities/utilities.py -> build/lib/ragoo_utilities
copying ragoo_utilities/break_chimera.py -> build/lib/ragoo_utilities
copying ragoo_utilities/__init__.py -> build/lib/ragoo_utilities
copying ragoo_utilities/get_contig_borders.py -> build/lib/ragoo_utilities
copying ragoo_utilities/ContigAlignment.py -> build/lib/ragoo_utilities
copying ragoo_utilities/get_ragoo_stats.py -> build/lib/ragoo_utilities
copying ragoo_utilities/PAFReader.py -> build/lib/ragoo_utilities
warning: build_py: byte-compiling is disabled, skipping.

creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ragoo_utilities
copying build/lib/ragoo_utilities/utilities.py -> build/bdist.linux-x86_64/egg/ragoo_utilities
copying build/lib/ragoo_utilities/__init__.py -> build/bdist.linux-x86_64/egg/ragoo_utilities
copying build/lib/ragoo_utilities/break_chimera.py -> build/bdist.linux-x86_64/egg/ragoo_utilities
copying build/lib/ragoo_utilities/GFFReader.py -> build/bdist.linux-x86_64/egg/ragoo_utilities
copying build/lib/ragoo_utilities/get_contig_borders.py -> build/bdist.linux-x86_64/egg/ragoo_utilities
copying build/lib/ragoo_utilities/SeqReader.py -> build/bdist.linux-x86_64/egg/ragoo_utilities
copying build/lib/ragoo_utilities/PAFReader.py -> build/bdist.linux-x86_64/egg/ragoo_utilities
copying build/lib/ragoo_utilities/get_ragoo_stats.py -> build/bdist.linux-x86_64/egg/ragoo_utilities
copying build/lib/ragoo_utilities/ContigAlignment.py -> build/bdist.linux-x86_64/egg/ragoo_utilities
warning: install_lib: byte-compiling is disabled, skipping.

creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying setup.py -> build/scripts-2.7
copying ragoo.py -> build/scripts-2.7
copying and adjusting sam2delta.py -> build/scripts-2.7
copying lift_over.py -> build/scripts-2.7
copying Assemblytics_between_alignments.pl -> build/scripts-2.7
copying and adjusting Assemblytics_within_alignment.py -> build/scripts-2.7
copying and adjusting Assemblytics_uniq_anchor.py -> build/scripts-2.7
copying filter_gap_SVs.py -> build/scripts-2.7
changing mode of build/scripts-2.7/setup.py from 664 to 775
changing mode of build/scripts-2.7/ragoo.py from 664 to 775
changing mode of build/scripts-2.7/sam2delta.py from 664 to 775
changing mode of build/scripts-2.7/lift_over.py from 664 to 775
changing mode of build/scripts-2.7/Assemblytics_within_alignment.py from 664 to 775
changing mode of build/scripts-2.7/Assemblytics_uniq_anchor.py from 664 to 775
changing mode of build/scripts-2.7/filter_gap_SVs.py from 664 to 775
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/filter_gap_SVs.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/Assemblytics_uniq_anchor.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/Assemblytics_between_alignments.pl -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/lift_over.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/ragoo.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/setup.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/sam2delta.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/Assemblytics_within_alignment.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/filter_gap_SVs.py to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/Assemblytics_uniq_anchor.py to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/Assemblytics_between_alignments.pl to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/lift_over.py to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/ragoo.py to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/setup.py to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sam2delta.py to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/Assemblytics_within_alignment.py to 775
copying RaGOO.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying RaGOO.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying RaGOO.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying RaGOO.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying RaGOO.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying RaGOO.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/RaGOO-1.2-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing RaGOO-1.2-py2.7.egg
Copying RaGOO-1.2-py2.7.egg to /home/fc464/software/RaGOO/RaGOO_env/lib/python2.7/site-packages
Removing RaGOO 1.2 from easy-install.pth file
Adding RaGOO 1.2 to easy-install.pth file
Installing Assemblytics_within_alignment.py script to /home/fc464/software/RaGOO/RaGOO_env/bin
Installing filter_gap_SVs.py script to /home/fc464/software/RaGOO/RaGOO_env/bin
Installing sam2delta.py script to /home/fc464/software/RaGOO/RaGOO_env/bin
Installing lift_over.py script to /home/fc464/software/RaGOO/RaGOO_env/bin
Installing Assemblytics_between_alignments.pl script to /home/fc464/software/RaGOO/RaGOO_env/bin
Installing Assemblytics_uniq_anchor.py script to /home/fc464/software/RaGOO/RaGOO_env/bin
Installing setup.py script to /home/fc464/software/RaGOO/RaGOO_env/bin
Installing ragoo.py script to /home/fc464/software/RaGOO/RaGOO_env/bin

Installed /home/fc464/software/RaGOO/RaGOO_env/lib/python2.7/site-packages/RaGOO-1.2-py2.7.egg
Processing dependencies for RaGOO==1.2
Searching for numpy==1.16.2
Best match: numpy 1.16.2
Adding numpy 1.16.2 to easy-install.pth file
Installing f2py2 script to /home/fc464/software/RaGOO/RaGOO_env/bin
Installing f2py script to /home/fc464/software/RaGOO/RaGOO_env/bin
Installing f2py2.7 script to /home/fc464/software/RaGOO/RaGOO_env/bin

Using /home/fc464/software/RaGOO/RaGOO_env/lib/python2.7/site-packages
Searching for intervaltree==3.0.2
Best match: intervaltree 3.0.2
Adding intervaltree 3.0.2 to easy-install.pth file

Using /home/fc464/software/RaGOO/RaGOO_env/lib/python2.7/site-packages
Searching for sortedcontainers==2.1.0
Best match: sortedcontainers 2.1.0
Adding sortedcontainers 2.1.0 to easy-install.pth file

Using /home/fc464/software/RaGOO/RaGOO_env/lib/python2.7/site-packages
Finished processing dependencies for RaGOO==1.2
```

**Comment by francicco** [comment]
It looks like virtualenv make use of the python 2.7

**Comment by malonge** [comment]
Yeah, RaGOO depends on python3, so hopefully, you can get a pytho3 virtualenv going. If not, anaconda is a nice option too.

**Comment by francicco** [comment]
Virtualenv with python3 is not working...
with miniconda:

```
[fc464@login-e-10 ~]$ conda install ragoo
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ragoo

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/r/linux-64
  - https://conda.anaconda.org/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by francicco** [comment]
<img width="987" alt="screenshot 2019-03-05 at 15 14 45" src="https://user-images.githubusercontent.com/9006870/53815365-72ab9f00-3f59-11e9-9f5a-2e724360211d.png">

**Comment by malonge** [comment]
Yeah that command will not work - you still need to do something like this:
```
$cd RaGOO
$~/anaoconda3/bin/python3 setup.py install
```

Then the excutable will be:

`$~/anaoconda3/bin/ragoo.py`

or

```
$~/anaconda3/bin/virtualenv VE
$. VE/bin/activate
$cd RaGOO
$python setup.py install
```

Just replace `~/anaconda3` with wherever you installed conda. 

Either way, you are still using the `python setup install` syntax, but just ensuring that you are doing so whith a python3 interpreter. 

Hope this helps

**Comment by francicco** [comment]
Updating pip worked

```
(RaGOO_env) [fc464@login-e-10 RaGOO]$ python ragoo.py
usage: ragoo.py [-h] [-e <exclude.txt>] [-gff <annotations.gff>] [-m PATH]
                [-b] [-t 3] [-g 100] [-s] [-i 0.2] [-j <skip.txt>]
                <contigs.fasta> <reference.fasta>
ragoo.py: error: the following arguments are required: <contigs.fasta>, <reference.fasta>
```

Now, let's test it!!! ;)

**Comment by malonge** [comment]
Great, let me know if you run into any other problem.

**Comment by francicco** [comment]
it produced a single contig:

Parsing ragoo.fasta
____________________________
N50: 463827447
Number of contigs: 1
Longest contig: 463827447
Genome length: 463827447

**Comment by fbemm** [comment]
Any plans to push ragoo to bioconda? Would be great for automatic installation in SnakeMake.

**Comment by malonge** [comment]
@fbemm I have thought about it - it is probably about time now that I have added the latest updates.

If you open up a separate issue I can keep you updated on progress.

Thanks
