### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by droeatumn** [malonge/RaGOO#57]
I'm trying a trival test to where the contig is the same as the ~160kb reference (attached). I am running v1.1 on OSX 10.15.4. This is what happens:

```
ragoo.py KP420442.fasta KP420442.fasta 
Traceback (most recent call last):
  File "/usr/local/bin/ragoo.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.1', 'ragoo.py')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/RaGOO-1.1-py2.7.egg/EGG-INFO/scripts/ragoo.py", line 11, in <module>
    
  File "build/bdist.macosx-10.15-x86_64/egg/ragoo_utilities/ContigAlignment.py", line 4, in <module>
  File "/Library/Python/2.7/site-packages/RaGOO-1.1-py2.7.egg/ragoo_utilities/utilities.py", line 30
    print(time.ctime() + ' --- ' + message, flush=True)

```
[KP420442.fasta.gz](https://github.com/malonge/RaGOO/files/4430293/KP420442.fasta.gz)

**Comment by malonge** [comment]
Hi there,

I apologize for the late reply. I have been busy submitting a paper, but soon I will download your data and see if I can reproduce the error.

**Comment by malonge** [comment]
I am unable to reproduce your error and RaGOO runs to completion on your test data. I think this is actually an installation issue. It looks like you have installed with python2.7. Please install with python3 and see if the problem persists.

Thanks

**Comment by droeatumn** [comment]
Yes, that was it. Thank you.
