### ISSUE TITLE
ValueError in filter_gap_SVs.py (get_query_bed_coords)

### ISSUE THREAD

**Issue by alexisnorris** [malonge/RaGOO#59]
Hi Michael,

Thanks for the great tool and documentation! I went through previous issues and wiki, but I couldn't find cause/solution for the following error at the `get_query_bed_coords` of `filter_gap_SVs.py` when I use `-s -b -g 100 -i 0.2 -C`:

```
ValueError: invalid literal for int() with base 10: '10733601_RaGOO'
```

I'm aligning a couple of `contig.fasta` each with two `reference.fasta`. I'm only getting the error for one combination of `contig.fasta` and `reference.fasta`. 

Thanks!
Alexis

```
Thu Apr 16 14:18:11 2020 --- Running : filter_gap_SVs.py ../../reference.fasta
Traceback (most recent call last):
  File "/work/virtualenvs/venv_devopspy/bin/filter_gap_SVs.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.1', 'filter_gap_SVs.py')
  File "/work/virtualenvs/venv_devopspy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/work/virtualenvs/venv_devopspy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/work/virtualenvs/venv_devopspy/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/EGG-INFO/scripts/filter_gap_SVs.py", line 135, in <module>
  File "/work/virtualenvs/venv_devopspy/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/EGG-INFO/scripts/filter_gap_SVs.py", line 131, in main
  File "/work/virtualenvs/venv_devopspy/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/EGG-INFO/scripts/filter_gap_SVs.py", line 69, in make_svs_bed
  File "/work/virtualenvs/venv_devopspy/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/EGG-INFO/scripts/filter_gap_SVs.py", line 52, in get_query_bed_coords
ValueError: invalid literal for int() with base 10: '10733601_RaGOO'
Traceback (most recent call last):
  File "/work/virtualenvs/venv_devopspy/bin/ragoo.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.1', 'ragoo.py')
  File "/work/virtualenvs/venv_devopspy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/work/virtualenvs/venv_devopspy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/work/virtualenvs/venv_devopspy/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/EGG-INFO/scripts/ragoo.py", line 757, in <module>
  File "/work/virtualenvs/venv_devopspy/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/EGG-INFO/scripts/ragoo.py", line 480, in get_SVs
  File "/work/virtualenvs/venv_devopspy/lib/python3.6/site-packages/RaGOO-1.1-py3.6.egg/ragoo_utilities/utilities.py", line 25, in run
RuntimeError: Failed : filter_gap_SVs.py ../../reference.fasta 
```

**Comment by malonge** [comment]
Hi there

I have a guess as to what is happening. Is there ":" characters in your reference headers?

**Comment by alexisnorris** [comment]
Thanks for the quick reply.

I ran `samtools faidx` to double check fasta headers for both `reference.fasta` and `contig.fasta`. 
- `reference.fasta`: all "chr" and number or X, Y, MT -- no spaces, ":", "_", "-", or ";" characters
- `contig.fasta`: polished primary contigs from FALCON-arrow, so "000001F|arrow", "000002F|arrow", etc.

The strange thing is that the `reference.fasta works fine for the same sample's haplotigs and both the primary contigs and haplotigs for a second sample. And this `contig.fasta` works fine with my other `reference.fasta`. My two `reference.fasta` files are full genomes from two different mammals.

**Comment by malonge** [comment]
That is interesting. Can you share a representative header from ragoo.fasta. From your error message, I would expect something to have the suffix `10733601_RaGOO`

**Comment by alexisnorris** [comment]
I found the culprit:
`000065F|arrow_chimera_broken:10520800-10733601_RaGOO`

Should I not be using `-c` (Break chimeric contigs) with SV calling? Or insert a step to rename/exclude these before SV calling? 

One thing I noticed: `000065F|arrow_chimera_broken:10520800-10733601_RaGOO` is very large (200kb). All of the `ragoo.fasta` from successful runs have broken chimeric contigs < 33kb (all but one are <1kb).

**Comment by malonge** [comment]
oops, my apologies. This is an unplaced contig that was broken during chimeric contig correction. In hindsight, I shouldn't be putting the "_RaGOO" suffix on these (that will not happen in v2), though that is not relevant here.

Stay tuned for an update that addresses this.

**Comment by malonge** [comment]
oops, my apologies. This is an unplaced contig that was broken during chimeric contig correction. In hindsight, I shouldn't be putting the "_RaGOO" suffix on these (that will not happen in v2), though that is not relevant here.

Stay tuned for an update that addresses this.

**Comment by malonge** [comment]
This bug should be fixed in 030bb1ba48c4992509111a0321b290f226dc88c0.

Please verify and I will close the issue.

**Comment by alexisnorris** [comment]
Success! It's working. Thanks so much!

**Comment by malonge** [comment]
You are welcome. Thanks for bringing this to my attention.
