### ISSUE TITLE
unable to detect data files for Ragoo

### ISSUE THREAD

**Issue by jainv45** [malonge/RaGOO#62]
(virtual) C:\Users\hp\virtual\Scripts>ragoo.py contigs.fa reference.fa
Sun May  3 16:11:01 2020 --- Running : minimap2 -k19 -w19 -t3 ../11801.gb ../contigs.fa > contigs_against_ref.paf 2> contigs_against_ref.paf.log
Traceback (most recent call last):
  File "C:\Users\hp\virtual\Scripts\ragoo.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.1', 'ragoo.py')
  File "C:\Users\hp\virtual\lib\site-packages\pkg_resources\__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\hp\virtual\lib\site-packages\pkg_resources\__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "C:\Users\hp\virtual\lib\site-packages\ragoo-1.1-py3.8.egg\EGG-INFO\scripts\ragoo.py", line 585, in <module>
  File "C:\Users\hp\virtual\lib\site-packages\ragoo-1.1-py3.8.egg\ragoo_utilities\utilities.py", line 24, in run
  File "c:\users\hp\appdata\local\programs\python\python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\hp\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\hp\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 3] The system cannot find the path specified

Have installed Ragoo in this virtual env. itself.
The data files are copied to this directory and this error is encountered when command executed. Still, it generates an empty output folder in the directory. I have tried with the symbolic link also.
Where am I going wrong?

**Comment by malonge** [comment]
Hi there,

In your example command, the reference genome is `reference.fa` but according to the logs, the reference is `11801.gb`.

Is that the exact command you used or is it just an example?

**Comment by cmonat** [comment]
Hello,

I have similar error. I am trying to run RaGOO on a SLURM cluster, so I want to transfer my files from my directory to the SCRACHDIR and then run RaGOO (and so minimap2). 

In my slurm job the command line I've used is:
`ragoo.py $SCRATCHDIR/R_v8_polished.fasta $SCRATCHDIR/Refv1.fasta -t 10`

And the error I've got is:
`Wed May  6 10:31:13 2020 --- Running : minimap2 -k19 -w19 -t10 ..//storage/scratch/celmonat/27980705/Refv1.fasta ..//storage/scratch/celmonat/27980705/R_v8_polished.fasta > contigs_against_ref.paf 2> contigs_against_ref.paf.log
Traceback (most recent call last):
  File "/opt/apps/python-3.7.1/gcc-8.1.0/RaGOO-1.11/bin/ragoo.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.1', 'ragoo.py')
  File "/opt/apps/gcc-8.1.0/python-3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/apps/gcc-8.1.0/python-3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/apps/python-3.7.1/gcc-8.1.0/RaGOO-1.11/lib/python3.7/site-packages/RaGOO-1.1-py3.7.egg/EGG-INFO/scripts/ragoo.py", line 580, in <module>
  File "/opt/apps/python-3.7.1/gcc-8.1.0/RaGOO-1.11/lib/python3.7/site-packages/RaGOO-1.1-py3.7.egg/ragoo_utilities/utilities.py", line 25, in run
RuntimeError: Failed : minimap2 -k19 -w19 -t10 ..//storage/scratch/celmonat/27980705/Refv1.fasta ..//storage/scratch/celmonat/27980705/R_v8_polish
ed.fasta > contigs_against_ref.paf 2> contigs_against_ref.paf.log
slurm-27980705.out (END)`

Do you have any idea how I can proceed to resolve this issue.
Is it a way to furnish to RaGOO an already done .paf file of minimap2? Because I have tried minimap2 with the same parameters on the same files and its working perfectly.
Thanks in advance for your help

Cheers
C.

**Comment by malonge** [comment]
Hi there, 

Unfortunately, RaGOO v1 requires the fasta files to be present in the current working directory, which I realize can be an inconvenience for situations like this. This will be fixed in the forthcoming v2. 

If you have permissions, perhaps you can create a symbolic link for the fast files before running?

Thanks

**Comment by malonge** [comment]
I will close this but please reopen if anything comes up.

Also, please consider using [RagTag](https://github.com/malonge/RagTag) which allows users to specify paths for input files.
