### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '653057_RaGOO'

### ISSUE THREAD

**Issue by jithinjb** [malonge/RaGOO#71]
Hi Malonge.

I am getting the below error when I use float values for the flag -i. If I use an integer value, the job runs fine. Could you please give me your comments on this?

Loading ragoon/python3/1.11
  Loading requirement: python3 minimap2/gcc-9.2.0/2.17
Traceback (most recent call last):
  File "/cm/shared/apps/ragoo/python3/1.11/bin/filter_gap_SVs.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.1', 'filter_gap_SVs.py')
  File "/cm/local/apps/python3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/cm/local/apps/python3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/cm/shared/apps/ragoo/python3/1.11/lib/python3.7/site-packages/RaGOO-1.1-py3.7.egg/EGG-INFO/scripts/filter_gap_SVs.py", line 125, in <module>
  File "/cm/shared/apps/ragoo/python3/1.11/lib/python3.7/site-packages/RaGOO-1.1-py3.7.egg/EGG-INFO/scripts/filter_gap_SVs.py", line 121, in main
  File "/cm/shared/apps/ragoo/python3/1.11/lib/python3.7/site-packages/RaGOO-1.1-py3.7.egg/EGG-INFO/scripts/filter_gap_SVs.py", line 59, in make_svs_bed
  File "/cm/shared/apps/ragoo/python3/1.11/lib/python3.7/site-packages/RaGOO-1.1-py3.7.egg/EGG-INFO/scripts/filter_gap_SVs.py", line 42, in get_query_bed_coords
ValueError: invalid literal for int() with base 10: '653057_RaGOO'
Traceback (most recent call last):
  File "/cm/shared/apps/ragoo/python3/1.11/bin/ragoo.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.1', 'ragoo.py')
  File "/cm/local/apps/python3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/cm/local/apps/python3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
@
"stderr_file" 25L, 2284C

**Comment by malonge** [comment]
Hi there,

Could you share your command?

Also, if you are not too invested yet, I recommend you switch to using the new and improved version of RaGOO which is called RagTag:

https://github.com/malonge/RagTag

It's the same idea as RaGOO though a little more accurate and with a lot of nice new features. Regardless, I am happy to take a look into this RaGOO issue.

Thanks,
Mike

**Comment by jithinjb** [comment]
Hi Mike,

Thanks for the reply. Following the command I used " **ragoo.py Iaq6.scaffolds.fa NSP306_trifida_chr_v3.fa -b -t 40 -g 100 -s -i 0.2 -C** "


Regards,
Jithin

**Comment by malonge** [comment]
Please reopen the issue if anything comes up. Thanks
