### ISSUE TITLE
RuntimeError: Failed

### ISSUE THREAD

**Issue by luo123675** [malonge/RaGOO#81]
Fri Apr  2 10:42:44 2021 --- Running : /public/home/miniconda3/bin/minimap2 -k19 -w19 -t3 ..//public/home/ragoo/GCF_000298735.2_Oar_v4.0_genomic.fa ..//public/home/ragoo/hu.contig.fa > contigs_against_ref.paf 2> contigs_against_ref.paf.log
Traceback (most recent call last):
  File "/public/home/soft/RaGOO-master/build/scripts-3.8/ragoo.py", line 585, in <module>
    run(cmd)
  File "/public/home/miniconda3/lib/python3.8/site-packages/RaGOO-1.1-py3.8.egg/ragoo_utilities/utilities.py", line 25, in run
** RuntimeError: Failed : miniconda3/bin/minimap2 -k19 -w19 -t3 ..//public/home/ragoo/GCF_000298735.2_Oar_v4.0_genomic.fa ..//public/home/ragoo/hu.contig.fa > contigs_against_ref.paf 2> contigs_against_ref.paf.log** 

This is the contents of my error file
can you help me ?

**Comment by luo123675** [comment]
and   why   [ERROR] failed to open file '..//public/home/ragoo/reference_genomic.fa'?


thank you very much

**Comment by malonge** [comment]
Hi there,

RaGOO is no longer supported. Please use [RagTag](https://github.com/malonge/RagTag) instead.
